name: My First GitHub Actions File

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello Prii, GitHub Actions is working"

      - name: Show current working directory
        run: pwd

      - name: Show list of files
        run: ls -l
